stages:
  data_ingestion:
    cmd: python3 main.py
    deps:
      - main.py
      - WineQuality/pipeline/stage_01_data_ingestion.py
      - WineQuality/pipeline/stage_02_data_validation.py
      - WineQuality/pipeline/stage_03_data_transformation.py
      - WineQuality/pipeline/stage_04_model_trainer.py
      - WineQuality/pipeline/stage_05_model_evaluation.py
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python3 main.py
    deps:
      - main.py
      - WineQuality/pipeline/stage_02_data_validation.py
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python3 main.py
    deps:
      - main.py
      - WineQuality/pipeline/stage_03_data_transformation.py
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  model_trainer:
    cmd: python3 main.py
    deps:
      - main.py
      - WineQuality/pipeline/stage_04_model_trainer.py
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python3 main.py
    deps:
      - main.py
      - WineQuality/pipeline/stage_05_model_evaluation.py
    outs:
      - artifacts/model_evaluation/metrics.json
