stages:
  data_ingestion:
    cmd: python src/WineQuality/pipeline/stage_01_data_ingestion.py
    deps:
      - src/WineQuality/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python src/WineQuality/pipeline/stage_02_data_validation.py
    deps:
      - src/WineQuality/pipeline/stage_02_data_validation.py
      - artifacts/data_ingestion/winequality-red.csv
      - config/config.yaml
    outs:
      - artifacts\data_validation\status.txt
